version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: feedback
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
